ComicBookGallery/src/ComicBookGallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

ComicBookGallery/src/ComicBookGallery/Models/ComicBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ComicBookGallery.Models
{
    public class ComicBook
    {
        public int Id { get; set; }
        public string SeriesTitle{ get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHTML { get; set; }
        public Artist[] Artists { get; set; }
        public bool Favorite { get; set; }
        
        public string DisplayText
        {
            get
            {
                return SeriesTitle + " #" + IssueNumber;
            }
        }

        // series-title-issuenumber.jpg
        public string CoverImageFileName
        {
            get
            {
                return SeriesTitle.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
            }
        }
    }
}

ComicBookGallery/src/ComicBookGallery/Models/ContactMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ComicBookGallery.Models
{
    public class ContactMessage
    {
        public enum ContactPersoonEnum
        {
            Particulier,
            Bedrijf
        }

        //Constructor no params
        public ContactMessage()
        {

        }

        public ContactMessage(DateTime date ,int contactMessageId, string naam, string email, ContactPersoonEnum contactPersoon, string telefoon, string boodschap)
        {
            Date = date;
            ContactMessageId = contactMessageId;
            Naam = naam;
            Email = email;
            ContactPersoon = contactPersoon;
            Telefoon = telefoon;
            Boodschap = boodschap;

        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Gelieve een correcte datum in te vullen.")]
        public DateTime Date { get; set; }

        public int ContactMessageId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Gelieve het Naam veld in te vullen.")]
        [RegularExpression("^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$", ErrorMessage = "Gelieve enkel tekens uit het alfabet te gebruiken om u naam in te vullen")]
        public string Naam { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Gelieve het Email veld in te vullen.")]
        [EmailAddress(ErrorMessage = "Gelieve een correct email adres in te vullen.")]
        public string Email { get; set; }

        public ContactPersoonEnum ContactPersoon { get; set; }

        
        public string Telefoon { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Gelieve een Boodschap in te vullen")]
        public string Boodschap { get; set; }


    }
}

ComicBookGallery/src/ComicBookGallery/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicBookGallery.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

ComicBookGallery/src/ComicBookGallery/Controllers/ComicBooksController.cs
using ComicBookGallery.Data;
using ComicBookGallery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComicBookGallery.Controllers
{
    public class ComicBooksController: Controller
    {
        private ComicBookRepository _comicBookRepository = null;

        public ComicBooksController()
        {
            _comicBookRepository = new ComicBookRepository();
        }


        public ActionResult Index()
        {
            var comicBooks = _comicBookRepository.GetComicBooks();
            return View(comicBooks);
        }

        public ActionResult Detail(int? id)
        {
            if(id == null)
            {
                return HttpNotFound();
            }
            var comicBook = _comicBookRepository.GetComicBook(id.Value);
            return View(comicBook);
            
        }
    }
}

ComicBookGallery/src/ComicBookGallery/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComicBookGallery.Data;
using ComicBookGallery.Models;
using System.Threading;

namespace ComicBookGallery.Controllers
{
    public class ContactController : Controller
    {
        private ContactMessageRepository _contactMessageRepository = null;

        public ContactController()
        {
            _contactMessageRepository = new ContactMessageRepository();
        }


        //Wanneer de pagina eerste maal wordt gegenereerd in de sessie
        // GET: Contact
        
        public ActionResult Index()
        {
            
            var contactMessage = new ContactMessage()
            {
                Date = DateTime.Today
            };
            return View(contactMessage);
        }

        //Wanneer er een Post van de form (een nieuwe contactmessage wordt verstuurd) wordt uitgevoerd of wanneer de modelstate niet Valid is
        [HttpPost]
        public ActionResult Index(ContactMessage contactMessage)
        {
            
            if (ModelState.IsValid)
            {
                // Get the next available Message ID.
                int nextAvailableEntryId = ContactMessageRepository._contactMessages
                    .Max(e => e.ContactMessageId) + 1;

                contactMessage.ContactMessageId = nextAvailableEntryId;

                ContactMessageRepository._contactMessages.Add(contactMessage);
                return RedirectToAction("ContactMessages");
            }
            return View(contactMessage);
        }

        //Alle contact messages opgelijst
        public ActionResult ContactMessages()
        {
            var contactMessages = _contactMessageRepository.getContactMessages();
            return View(contactMessages);
        }

        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            var contactMessage = _contactMessageRepository.GetContactMessage(id.Value);
                
            return View(contactMessage);
        }

        public ActionResult Delete (int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int messageId = Convert.ToInt32(id);

            _contactMessageRepository.DeleteContactMessage(messageId);

            return RedirectToAction("ContactMessages");

        }


    }
}

ComicBookGallery/src/ComicBookGallery/Views/About/Index.cshtml
@{
    ViewBag.Title = "About";
}

<h2>@ViewBag.Title</h2>

ComicBookGallery/src/ComicBookGallery/Views/ComicBooks/Detail.cshtml
@model ComicBookGallery.Models.ComicBook

@{
    //Layout = "~/Views/Shared/_Layout.cshtml"; -> reeds geset in Views -> _ViewStart.cshtml
    ViewBag.Title = Model.DisplayText;
    ViewBag.ShowBackBar = true;
}


<h2>@Model.DisplayText</h2>

<div class="row">
    <div class="col-md-6">
        <div class="well">
            <h5><label>Series Title:</label> @Model.SeriesTitle</h5>
            <h5><label>Issue #:</label> @Model.IssueNumber</h5>
            <h5><label>Favorite:</label> @(Model.Favorite ? "Yes" : "No")</h5>
            @if (Model.Artists.Length > 0)
            {
                <h5>Artists:</h5>
                <div>
                    <ul>
                        @foreach (var artist in Model.Artists)
                        {
                            <li>@artist.Role: @artist.Name</li>
                        }
                    </ul>
                </div>
            }
        </div>
        <h5>Description</h5>
        <p>@Html.Raw(Model.DescriptionHTML)</p>
    </div>
    <div class="col-md-6">
        <img src="/Images/@Model.CoverImageFileName"
             alt="@Model.DisplayText" class="img-responsive" />
    </div>
</div>

ComicBookGallery/src/ComicBookGallery/Views/ComicBooks/DisplayTemplates/IndexTop.cshtml
<div class="col-md-6">
    <h2>Welcome to the Comic Book Gallery</h2>
    <p>Your source for Comics of all kinds</p>
</div>
<div class="col-md-6" style="overflow: hidden">
    <img src="~/Images/comicbookjunkie-banner.jpg" alt="index-top-banner" class="img-responsive" />
</div>

<hr />

ComicBookGallery/src/ComicBookGallery/Views/ComicBooks/Index.cshtml
@model ComicBookGallery.Models.ComicBook[]

@{
    ViewBag.Title = "Comic Books";
}

@Html.Partial("DisplayTemplates/IndexTop")

<h2>@ViewBag.Title</h2>


<div class="row">
    @foreach (var comicbook in Model)
    {
        <div class="col-md-3">
            <h4 class="ComicBooks-comic-title-bar">@Html.ActionLink(comicbook.DisplayText, "Detail", new { id = comicbook.Id })</h4>
            <a href="@Url.Action("Detail", new { id = comicbook.Id})" ><img src="/Images/@comicbook.CoverImageFileName"alt="@comicbook.DisplayText" class="img-responsive" /></a>
        </div>
    }
    </div>

ComicBookGallery/src/ComicBookGallery/Views/Contact/ContactMessages.cshtml
@model List<ComicBookGallery.Models.ContactMessage>

@{
    ViewBag.Title = "Contact Messages";
}

<h2>@ViewBag.Title</h2>


<table class="table">
    <tr>
        <th>Date</th>
        <th>Afzender</th>
        <th>Email</th>
        <th>Soort</th>
        <th>Telefoon</th>
        <th>&nbsp;</th>
    </tr>

    
        @foreach (var contactMessage in Model)
        {
            <tr>
                <td>
                    <span class="hidden-xs">@contactMessage.Date.ToString("MM/dd/yyyy")</span>
                    <span class="hidden-sm hidden-md hidden-lg">@contactMessage.Date.ToString("MM/dd")</span>
                </td>

                <td>@contactMessage.Naam</td>

                <td>@contactMessage.Email</td>

                <td>@contactMessage.ContactPersoon.ToString()</td>

                <td>@contactMessage.Telefoon</td>

                <td>
                    <div class="pull-right">
                        <a href="@Url.Action("Detail", new { id = contactMessage.ContactMessageId })" class="btn btn-warning btn-sm margin-right">
                            <span class="glyphicon glyphicon-edit"></span><span class="hidden-xs"> Detail</span>
                        </a>
                        <a href="@Url.Action("Delete", new { id = contactMessage.ContactMessageId })" class="btn btn-danger btn-sm">
                            <span class="glyphicon glyphicon-trash"></span><span class="hidden-xs"> Delete</span>
                        </a>
                    </div>
                </td>

            </tr>

        } 

    </table>

ComicBookGallery/src/ComicBookGallery/Views/Contact/Detail.cshtml
@model ComicBookGallery.Models.ContactMessage
@{
    ViewBag.Title = "Detail " + @Model.ContactPersoon;
}

<h2>Detail @Model.Naam @Model.Date.ToString("d")</h2>

<div class="row">
    <div class="col-md-8">
        <div class="well">
            <h5><label><strong>Verzender:</strong></label> @Model.Naam</h5>
            <h5><label><strong>Datum:</strong></label> @Model.Date.ToString("d")</h5>
            <h5><label><strong>Email:</strong></label> @Model.Email</h5>
            <h5><label><strong>Telefoon:</strong></label> @Model.Telefoon</h5>
            <h5><label><strong>Soort:</strong></label> @Model.ContactPersoon.ToString()</h5>
            <h5><label><strong>Boodschap:</strong></label></h5>
            <div>
                @Model.Boodschap
            </div>
        </div>
    </div>
    
</div>

ComicBookGallery/src/ComicBookGallery/Views/Contact/Index.cshtml
@model ComicBookGallery.Models.ContactMessage
@using ComicBookGallery.Models

@{
    ViewBag.Title = "Contact";
}

<head>
    <link href="~/Content/Contact.css" rel="stylesheet" type="text/css" />
</head>

@Html.Partial("DisplayTemplates/IndexTop")

<p>* Required field</p>


<h2>@ViewBag.Title</h2>

<br />


@using (Html.BeginForm())
{

    @* Add if statement to prevent the error summary of showing when the page loads for the first time *@
    if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary("Volgende zaken werden niet correct ingevuld:", new { @class = "alert alert-danger" })
    }



<div class="Row">

    <div class="col-md-6">
        <div class="form-group">
            *
            @Html.LabelFor(m => m.Date, new { @class = "control-label" }):
            @Html.TextBoxFor(m => m.Date, "{0:d}", new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(m => m.Date, "", new { @class = "alert-danger" })
        </div>

        <div class="form-group">
            *
            @Html.LabelFor(m => m.Naam, new { @class = "control-label" }):
            @Html.TextBoxFor(m => m.Naam, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Naam, "", new { @class = "alert-danger" })
        </div>

        <div class="form-group">
            *
            @Html.LabelFor(m => m.Email, new { @class = "control-label" }):
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "alert-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Telefoon, new { @class = "control-label" }):
            @Html.TextBoxFor(m => m.Telefoon, new { @class = "form-control" })
        </div>

        <div class="form-group">
            *
            @Html.LabelFor(m => m.ContactPersoon, new { @class = "control-label" }):
            <div>
                <label class="radio-inline">
                    @Html.RadioButtonFor(m => m.ContactPersoon, ContactMessage.ContactPersoonEnum.Particulier) @ContactMessage.ContactPersoonEnum.Particulier
                </label>

                <label class="radio-inline">
                    @Html.RadioButtonFor(m => m.ContactPersoon, ContactMessage.ContactPersoonEnum.Bedrijf) @ContactMessage.ContactPersoonEnum.Bedrijf
                </label>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            *
            @Html.LabelFor(m => m.Boodschap, new { @class = "control-label" }):
            @Html.TextAreaFor(m => m.Boodschap, new { @class = "form-control form-control-text-area" })
            @Html.ValidationMessageFor(m => m.Boodschap, "", new { @class = "alert-danger" })
        </div>
    </div>

    

    <div class="col-md-12">
        <br />
        <br />
        <div class="pad-top">
            <button type="submit" class="btn btn-succes btn-lg margin-right">
                <span class="glyphicon glyphicon-save"></span> Verstuur
            </button>
            <a href="@Url.Action("Index","ComicBooks","Index")" class="btn btn-warning btn-lg">
                <span class="glyphicon glyphicon-remove"></span> Cancel
            </a>
        </div>
    </div>
</div>
    <div class="clearfix"></div>
}

ComicBookGallery/src/ComicBookGallery/Views/Shared/DisplayTemplates/IndexTop.cshtml
<div class="col-md-6">
    <h2>Welcome to the Comic Book Gallery</h2>
    <p>Your source for Comics of all kinds</p>
</div>
<div class="col-md-6" style="overflow: hidden">
    <img src="~/Images/comicbookjunkie-banner.jpg" alt="index-top-banner" class="img-responsive" />
</div>

<hr />

ComicBookGallery/src/ComicBookGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Comic Book Gallery</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Comic Book Gallery", "Index", "ComicBooks", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-right">
                    @Html.ActionLink("Products", "Index", "ComicBooks", new { area = "" }, new { @class = "navbar-text" })
                    @Html.ActionLink("About", "Index", "About", new { area = "" }, new { @class = "navbar-text" })
                    @Html.ActionLink("Contact", "Index", "Contact", new { area = "" }, new { @class = "navbar-text" })
                </ul>
            </div>
        </div>
    </div>

    @*@if (ViewBag.ShowBackBar != null && ViewBag.ShowBackBar)
        {
            <div class="backbar">
                <div class="container">
                    @Html.ActionLink("Return to ComicList", "Index", null, new { @class = "btn btn-default" })
                    @*<a class="btn btn-default" href="/">Return to List</a>   <- Bovenstaande action link vervangt de HTML Link tag
                </div>
            </div>
        }*@

    <div class="container body-content">
        @RenderBody()

        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - Comic Book Gallery</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @* Underlying 2 scripts were both obtained with nuget package manager as Jquery validation and Microsoft unobtruvsive jquery validion
        They are used for client side validation*@
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.date.js"></script> @*Steeds deze file bijvoegen om problemen met date validatie te vermijden !*@
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @* Underlying script makes validation field mark with checkmark or x mark if valid or unvalid! *@
    <script src="~/Scripts/jquery.bootstrap.validate.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.min.js"></script>
    @*Onderstaande maakt de datepicker bruikbaar via de datepicker css class  STEEDS SCRIPT EN CSS FILE BIJVOEGEN OOK*@
    @*<script>
        $('input.datepicker').datepicker({ format: 'm/d/yyyy' });
    </script>*@

</body>
</html>